openapi: 3.0.0
info:
  title: Vuelos API Ceste
  description: Una API para consultar vuelos
  version: 1.0.0

paths:
  /flights:
    get:
      operationId: get_flights
      parameters:
      - name: origin
        in: query
        schema:
          type: string
      - name: destination
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Lista de vuelos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flight'

components:
  schemas:
    Flight:
      type: object
      properties:
        origin:
          type: string
        destination:
          type: string
        departure_date:
          type: string
          format: date
        arrival_date:
          type: string
          format: date
        price:
          type: number