openapi: 3.0.0
info:
  title: "Curso Ceste Flask REST API"
  description: "API acerca de persona(s)"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - lname
      properties:
        fname:
          type: "string"
        lname:
          type: "string"
  parameters:
    lname:
      name: "lname"
      description: "Apellido de la persona a recibir"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Leer la lista de personas"
      responses:
        "200":
          description: "Lectura con éxito la lista de personas"
    post:
      operationId: "people.create"
      tags:
        - People
      summary: "Create a person"
      requestBody:
          description: "Persona a crear"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "person"
                $ref: "#/components/schemas/Person"
      responses:
        "201":
          description: "Persona creada con éxito"
  /people/{lname}:
    get:
      operationId: "people.read_one"
      tags:
        - People
      summary: "Leer una persona"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Persona leída exitosamente"
    put:
      tags:
        - People
      operationId: "people.update"
      summary: "Update a person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Persona actualizada exitosamente"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"
    delete:
      tags:
        - People
      operationId: "people.delete"
      summary: "Eliminar una persona"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "204":
          description: "Persona eliminada exitosamente"